version: "3"

services:
  web:
    build: .
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/myapp

  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - "27017"
    volumes:
      - ./msgdb/:/data/db
